weights: /content/yolov5s.pt
cfg: ''
data: /content/drive/MyDrive/ConfMix/data/Sim10K2Cityscapes.yaml
hyp: drive/MyDrive/ConfMix/data/hyps/hyp.scratch-low.yaml
epochs: 50
batch_size: 2
imgsz: 600
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 8
project: drive/MyDrive/ConfMix/runs/train
name: sim10k2cityscapes
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
local_rank: -1
max_det_pct: 100
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: drive/MyDrive/ConfMix/runs/train/sim10k2cityscapes4
